version: '3.4'

services:
  postgresdb:
    image: postgres
    restart: always
    networks:
      - webapi_network

  snmpmanager.webapi:
    image: ${DOCKER_REGISTRY-}snmpmanagerwebapi
    build:
      context: .
      dockerfile: Manager/SNMPManager.WebAPI/Dockerfile
    depends_on:
      - "postgresdb"
    networks:
      - webapi_network


networks:
  webapi_network:
    driver: bridge