version: '3.4'

services:
  snmpmanager.webapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_HTTPS_PORT: 44387
      DB: "Host=postgresdb;Database=webapi;Username=admin;Password=snmppass"
    ports:
      - "51467:80"
      - "44387:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  postgresdb:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: snmppass
      POSTGRES_DB: webapi