// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SNMPManager.Persistence;

namespace SNMPManager.Migrations
{
    [DbContext(typeof(ManagerContext))]
    partial class ManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SNMPManager.Database.Models.LogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("LogTypes");
                });

            modelBuilder.Entity("SNMPManager.Database.Models.ManagerLog", b =>
                {
                    b.Property<DateTime>("TimeStamp");

                    b.Property<int>("TypeId");

                    b.Property<string>("Message")
                        .IsRequired();

                    b.HasKey("TimeStamp", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("ManagerLogs");
                });

            modelBuilder.Entity("SNMPManager.Database.Models.RSU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(32);

                    b.Property<IPAddress>("IP")
                        .IsRequired();

                    b.Property<double>("Latitude");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(140);

                    b.Property<double>("Longitude");

                    b.Property<string>("MIBVersion")
                        .HasMaxLength(32);

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(32);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<IPAddress>("NotificationIP")
                        .IsRequired();

                    b.Property<int>("NotificationPort");

                    b.HasKey("Id");

                    b.ToTable("RSUs");
                });

            modelBuilder.Entity("SNMPManager.Database.Models.TrapLog", b =>
                {
                    b.Property<DateTime>("TimeStamp");

                    b.Property<int>("TypeId");

                    b.Property<int>("SourceRSU");

                    b.Property<string>("Message")
                        .IsRequired();

                    b.HasKey("TimeStamp", "TypeId", "SourceRSU");

                    b.HasAlternateKey("SourceRSU", "TimeStamp", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("TrapLogs");
                });

            modelBuilder.Entity("SNMPManager.Database.Models.ManagerLog", b =>
                {
                    b.HasOne("SNMPManager.Database.Models.LogType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SNMPManager.Database.Models.TrapLog", b =>
                {
                    b.HasOne("SNMPManager.Database.Models.LogType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
